const EVENT_TYPES  = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	USER__CONNECTED: "USER__CONNECTED",
	MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
	MESSAGE_SENT: "MESSAGE_SENT",
	USER__DISCONNECTED: "USER__DISCONNECTED",
	TYPING: "TYPING",
	VERIFY_USER: "VERIFY_USER",
	LOG_OUT: "LOG_OUT"
}

module.exports = EVENT_TYPES;  